name: SUPER PATCHER WITH CUSTOM GSI
permissions:
  contents: write
on:
  push:
    branches:
      - main  # Change this to your desired branch
  workflow_dispatch:
    inputs:
        DEVICE:
              description: ' Enter Your Device Name '
              required: true
              default: 'Samsung Galaxy A03'
        GSI:
              description: ' GSI Image Direct Link '
              required: true
              default: 'https://github.com/ponces/treble_build_aosp/releases/download/v2023.12.01/aosp-arm64-ab-gapps-14.0-20231201.img.xz'        
        NAME:
              description: 'Rom Name'
              required: true
              default: 'aosp-arm64-ab-gapps-14.0-a03.7z'
        VERSION:
              description: 'Baseband Version'
              required: true
              default: 'A035FXXU4CWI1'
        VENDOR:
              description: 'Enter Direct Link Of Your Vendor.img'
              required: true
              default: 'https://sourceforge.net/projects/a03-files/files/A035FXXU4CWI1/vendor.img'
        ODM:
              description: 'Enter Direct Link Of Your odm.img(leave default if your device does not have odm) '
              default: ' https://sourceforge.net/projects/a03-files/files/no-odm.txt '
        SUPER:
              description: 'Enter The Size Of Your Super Partition'
              required: true
              default: '6763315200'


jobs:
  Build:
    runs-on: ubuntu-latest

    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y zip xz-utils unzip p7zip-full
    - name: Installing Tools
      run: |
        git clone https://github.com/Exynos-nigg/lpunpack-lpmake-mirror.git lpbinary
        cd lpbinary
        bash install.sh
    - name: Downloading Your Vendor And Odm(if applicable)
      run: |
        cd lpbinary/binary
        wget ${{ github.event.inputs.VENDOR }}
        wget ${{ github.event.inputs.ODM }}
        if [ -f *.zip ]; then  unzip *.zip; fi
        if [ -f *.xz ]; then  unxz *.xz; fi
        wget -q https://sourceforge.net/projects/a03-files/files/product.img/download -O product.img
        wget -q https://sourceforge.net/projects/a03-files/files/system_ext.img/download -O system_ext.img
    - name: Downloading Your GSI And Extracting
      run: |
        cd lpbinary/binary
        wget -q ${{ github.event.inputs.GSI }}
        mkdir sys
        mv *.xz sys
        cd sys
        unxz *.xz
        mv *.img ../system.img
        cd ..
    - name: Packing
      run: |
        cd lpbinary/binary
        if [ -f odm.img ]; then  main=$(($(ls -nl odm.img | awk '{print $5}') + 2621440 +$(ls -nl system.img | awk '{print $5}') + $(ls -nl vendor.img | awk '{print $5}'))); fi
        if [ -f system_ext.img ]; then  main=$((2621440 + 2621440 +$(ls -nl system.img | awk '{print $5}') + $(ls -nl vendor.img | awk '{print $5}'))); fi
        echo $main > main.txt
        if [ -f system_ext.img ]; then  ./lpmake --metadata-size 65536 --super-name super --metadata-slots 2 --device super:${{ github.event.inputs.SUPER }} --group main:$(<main.txt) --partition system:readonly:$(ls -nl system.img | awk '{print $5}'):main --image system=system.img --partition vendor:readonly:$(ls -nl vendor.img | awk '{print $5}'):main --image vendor=vendor.img --partition product:readonly:$(ls -nl product.img | awk '{print $5}'):main --image product=product.img --partition system_ext:readonly:$(ls -nl system_ext.img | awk '{print $5}'):main --image system_ext=system_ext.img --sparse --output super.img; fi
        if [ -f odm.img ]; then  ./lpmake --metadata-size 65536 --super-name super --metadata-slots 2 --device super:${{ github.event.inputs.SUPER }} --group main:$(<main.txt) --partition system:readonly:$(ls -nl system.img | awk '{print $5}'):main --image system=system.img --partition vendor:readonly:$(ls -nl vendor.img | awk '{print $5}'):main --image vendor=vendor.img --partition product:readonly:$(ls -nl product.img | awk '{print $5}'):main --image product=product.img --partition odm:readonly:$(ls -nl odm.img | awk '{print $5}'):main --image odm=odm.img --sparse --output super.img; fi
        rm system.img && rm product.img && rm vendor.img && rm -f odm.img && rm -f system_ext.img
    - name: Creating tar and compressing to 7z
      run: |
        cd lpbinary/binary
        tar -cvf super.tar super.img
        rm -rf super.img
        7z a ${{ github.event.inputs.NAME }} super.tar
        rm -rf super.tar
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: lpbinary/binary/${{ github.event.inputs.NAME }}
        name: ${{ github.event.inputs.NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
            Device: ${{ github.event.inputs.DEVICE }}
            Version: ${{ github.event.inputs.VERSION }}
            Rom Name: ${{ github.event.inputs.NAME }}
            Flash: Extract the 7z file and flash through ODIN in AP Section.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
